#
# Defines environment variables.
#

#
# Editors
#

export EDITOR='vim'
export VISUAL='gvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

